- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: Vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: create Public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        cidr: "{{PubSub1Cidr}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: vprofile_pubsub1
      register: pubsub1_out

    - debug:
          var: pubsub1_out

    - name: create Public subnet 2 in zone2
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone2 }}"
          cidr: "{{PubSub2Cidr}}"
          state: "{{state}}"
          map_public: yes
          resource_tags:
            Name: vprofile_pubsub2
      register: pubsub2_out

    - debug:
          var: pubsub2_out


    - name: create Public subnet 3 in zone3
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone3 }}"
          cidr: "{{PubSub3Cidr}}"
          state: "{{state}}"
          map_public: yes
          resource_tags:
            Name: vprofile_pubsub3
      register: pubsub3_out

    - debug:
          var: pubsub3_out

    - name: create Private subnet 1 in zone1
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone1 }}"
          cidr: "{{PrivSub1Cidr}}"
          state: "{{state}}"
          map_public: yes
          resource_tags:
            Name: vprofile_privsub1
      register: privsub1_out

    - debug:
          var: privsub1_out

    - name: create Private subnet 2 in zone2
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone2 }}"
          cidr: "{{PrivSub2Cidr}}"
          state: "{{state}}"
          map_public: yes
          resource_tags:
            Name: vprofile_privsub2
      register: privsub2_out

    - debug:
          var: privsub2_out

    - name: create Private subnet 3 in zone3
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone3 }}"
          cidr: "{{PrivSub3Cidr}}"
          state: "{{state}}"
          map_public: yes
          resource_tags:
            Name: vprofile_privsub3
      register: privsub3_out

    - debug:
          var: privsub3_out

    - name: Internet gateway setup
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        state: "{{state}}"
        resource_tags:
          Name: vprofile_IGW
      register: igw_out

    - debug:
          var: igw_out

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        tags:
          Name: Vprofile-PubRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: pubRT_out

    - debug:
          var: pubRT_out

    - name: Create new NAT gateway and allocate new EIP if a NAT gateway does not exists
      ec2_vpc_nat_gateway:
        state: "{{ state }}"
        subnet_id: "{{ pubsub1_out.subnet.id }}"
        wait: yes
        region: "{{ region }}"
        if_exist_do_not_create: true
      register: NATGW_out

    - debug:
          var: NATGW_out

    - name: Set up Private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: Vprofile-PrivRT
        subnets:
          - "{{ privsub1_out.subnet.id }}"
          - "{{ privsub2_out.subnet.id }}"
          - "{{ privsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ NATGW_out.nat_gateway_id }}"
      register: privRT_out

    - debug:
        var: privRT_out

    - debug:
        var: "{{ item }}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igw_out.gateway_id
        - NATGW_out.nat_gateway_id
        - pubRT_out.route_table.id
        - privRT_out.route_table.id

    - set_fact:
        vpcid: "{{ vpcout.vpc.id }}"
        pubsub1id: "{{ pubsub1_out.subnet.id }}"
        pubsub2id: "{{ pubsub2_out.subnet.id }}"
        pubsub3id: "{{ pubsub3_out.subnet.id }}"
        privsub1id: "{{ privsub1_out.subnet.id }}"
        privsub2id: "{{ privsub2_out.subnet.id }}"
        privsub3id: "{{ privsub3_out.subnet.id }}"
        igwid: "{{ igw_out.gateway_id }}"
        NATGWid: "{{ NATGW_out.nat_gateway_id }}"
        pubRTid: "{{ pubRT_out.route_table.id }}"
        privRTid: "{{ privRT_out.route_table.id }}"
        cacheable: yes

    - name: Create variables file for VPC output
      copy:
        content: "vpcid: {{ vpcout.vpc.id }}\npubsub1id: {{ pubsub1_out.subnet.id }}\npubsub2id: {{ pubsub2_out.subnet.id }}\npubsub3id: {{ pubsub3_out.subnet.id }}\nprivsub1id: {{ privsub1_out.subnet.id }}\nprivsub2id: {{ privsub2_out.subnet.id }}\nprivsub3id: {{ privsub3_out.subnet.id }}\nigwid: {{ igw_out.gateway_id }}\nNATGWid: {{ NATGW_out.nat_gateway_id }}\npubRTid: {{ pubRT_out.route_table.id }}\nprivRTid: {{ privRT_out.route_table.id }}"
        dest: Vars/output_vars
