- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: Vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: create Public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile_pubsub1
      register: pubsub1_out

    - name: create Public subnet 2 in zone2
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone2 }}"
          cidr: "{{PubSub2Cidr}}"
          map_public: yes
          resource_tags:
            Name: vprofile_pubsub2
      register: pubsub2_out

    - name: create Public subnet 3 in zone3
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone3 }}"
          cidr: "{{PubSub3Cidr}}"
          map_public: yes
          resource_tags:
            Name: vprofile_pubsub3
      register: pubsub1_out

    - name: create Private subnet 1 in zone1
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone1 }}"
          cidr: "{{PrivSub1Cidr}}"
          map_public: yes
          resource_tags:
            Name: vprofile_privsub1
      register: privsub1_out

    - name: create Private subnet 2 in zone2
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone2 }}"
          cidr: "{{PrivSub2Cidr}}"
          map_public: yes
          resource_tags:
            Name: vprofile_privsub2
      register: privsub2_out

    - name: create Private subnet 3 in zone3
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          region: "{{ region }}"
          az: "{{ zone3 }}"
          cidr: "{{PrivSub3Cidr}}"
          map_public: yes
          resource_tags:
            Name: vprofile_privsub3
      register: privsub3_out